#!/bin/bash

if [[ $# -lt 1 ]]; then
    echo "Usage: ./runAll <group> [batchsize] [partition (default: msismall)]"
    exit 1
fi

GROUP=$1
TOTAL_SAMPLES=$(wc -l /scratch.global/neis/bakeoff/${GROUP}/samples.txt | awk '{print $1}')
DONE_SAMPLES=$(find /scratch.global/neis/bakeoff/${GROUP}/ -name "*FINAL.vcf.gz.tbi" | wc -l)
REMAINING_SAMPLES=$((${TOTAL_SAMPLES} - ${DONE_SAMPLES}))
EXCLUSION="1000G"

if [[ -n $2 ]]; then
    BATCHSIZE=$2
else
    BATCHSIZE=${REMAINING_SAMPLES}
fi

if [[ -n $3 ]]; then
    partition=$3
else
    partition="msismall"
fi
RANK=1
CUR_BATCH=$(sbatch --parsable -p ${partition} --export=GROUP=${GROUP},REMAINING_SAMPLES=${REMAINING_SAMPLES},BATCHSIZE=${BATCHSIZE},EXCLUSION=${EXCLUSION},RANK=${RANK} rufus_docker_nonarray.slrm)
for ((i=1; i< BATCHSIZE; i++)); do
    RANK=$((i + 1))
    CUR_BATCH=$(sbatch --parsable -p ${partition} --export=GROUP=${GROUP},REMAINING_SAMPLES=${REMAINING_SAMPLES},BATCHSIZE=${BATCHSIZE},EXCLUSION=${EXCLUSION},RANK=${RANK} rufus_docker_nonarray.slrm)
done

sbatch --dependency=afterany:${CUR_BATCH} backup_rufus.slrm

find /scratch.global/neis/bakeoff/ ! -name "*.auxindex" -mtime +15 -exec touch {} \;