#!/bin/bash
GROUP=$1
TOTAL_SAMPLES=$(wc -l /scratch.global/neis/bakeoff/${GROUP}/samples.txt | awk '{print $1}')
CHUNKSIZE=$2

sbatch --array=1-${CHUNKSIZE} -p amd512 --export=TOTAL_SAMPLES=${TOTAL_SAMPLES},OFFSET=0,GROUP=${GROUP} rufus_docker.slrm

